### ISSUE TITLE
README documentation link points to a crate that does not exist

### ISSUE THREAD

**Issue by lucasstarsz** [ANF/pastemyst-rs#29]
In the [README.md](https://github.com/ANF/pastemyst-rs/blob/main/README.MD) file, the red-boxed link shown:
![image](https://user-images.githubusercontent.com/64715411/107892080-c6b6b080-6ef0-11eb-8d29-1f0ceacc7cd5.png)

currently points to https://docs.rs/pastemyst-rs/*/, which is not a valid crate.

**Comment by tomlin7** [comment]
![image](https://user-images.githubusercontent.com/70792552/107923452-72034c00-6f69-11eb-8e20-28401965b5f1.png)
